#!/bin/bash
set -e

base_dir="/etc/libvirt/hooks"

object_name="$1"
operation="$2"
sub_operation="$3"
extra_arg="$4"

script_path="$base_dir/qemu.d/$object_name/$operation/$sub_operation"

if [ -x $script_path ]; then
    $script_path "$@"
fi
