#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o nounset

info() {
    echo "[info]" "$@"
}

err() {
    echo "[error]" "$@" 2>&1
}

die() {
    local code="$1"
    shift

    err "$@"
    exit "${code}"
}

__func_defered=()
do_defer() {
    for ((i=${#__func_defered[@]}-1;i>=0;i--)); do
        if ! eval "${__func_defered[i]}"; then
            die 1 "eval cmd failed, cmd: \"${__func_defered[i]}\""
        fi
    done
}
trap do_defer EXIT
defer() {
    __func_defered+=("$*")
}

opt_edk2="/usr/share/edk2-ovmf/x64/OVMF_CODE.4m.fd"
opt_rom="./assets/Gigabyte.RTX3090.24576.210315_3.rom"

opts_qemu=(
    "-nodefaults"
    "-vga" "none"
    "-nographic"

    "-machine" "q35,accel=kvm"
    "-cpu" "host"
    "-smp" "cores=32"
    "-m" "48G"
)

do_anti_detection() {
    opts_qemu+=(
        "-machine" "pc-q35-7.1,accel=kvm,usb=off,vmport=off,kernel_irqchip=on,dump-guest-core=off,hpet=off,acpi=on"
        "-cpu" "host,migratable=on,topoext=on,hypervisor=off,hv-time=on,hv-relaxed=on,hv-vapic=on,hv-spinlocks=0x1fff,hv-vendor-id=123456789ab,kvm=off,kvm-hint-dedicated=on"

        "-smbios" 'type=0,vendor=American Megatrends Inc.,version=0309,date=08/16/2021,release=5.17'
        "-smbios" 'type=1,manufacturer=System manufacturer,product=System Product Name,version=System Version,serial=System Serial Number,sku=SKU,family=To be filled by O.E.M.'
        "-smbios" 'type=2,manufacturer=ASUSTeK COMPUTER INC.,product=ROG STRIX X570-E GAMING WIFI II,version=Rev X.0x,serial=210890780700315,asset=Default string,location=Default string'
        "-smbios" 'type=3,manufacturer=Default string,version=Default string,serial=Default string,asset=Default string,sku=Default string'
        "-smbios" 'type=11,value=Default string,value=Default string,value=Default string,value=Default string,value=Default string,value=Default string,value=Default string,value=Default string'

        "-global" "kvm-pit.lost_tick_policy=delay"
        "-global" "ICH9-LPC.disable_s3=1"
        "-global" "ICH9-LPC.disable_s4=1"
        "-global" "ICH9-LPC.noreboot=off"

        "-sandbox" "on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny"
    )
}

do_nic_setup() {
    opts_qemu+=("-nic" "user")
}

do_gpu_passthrough() {
    virsh nodedev-detach pci_0000_01_00_0
    defer "virsh nodedev-reattach pci_0000_01_00_0"
    virsh nodedev-detach pci_0000_01_00_1
    defer "virsh nodedev-reattach pci_0000_01_00_1"

    opts_qemu+=(
        "-device" "vfio-pci,host=01:00.0,x-vga=on,multifunction=on,romfile=${opt_rom}"
        "-device" "vfio-pci,host=01:00.1"
    )
}

do_usb_passthrough() {
    virsh nodedev-detach pci_0000_69_00_0
    defer "virsh nodedev-reattach pci_0000_69_00_0"

    opts_qemu+=(
        "-device" "vfio-pci,host=69:00.0"
    )
}

main() {
    [ -n "${opt_edk2}" ] \
        && opts_qemu+=("-drive" "if=pflash,format=raw,readonly=on,file=${opt_edk2}")

    do_anti_detection
    do_nic_setup
    do_gpu_passthrough
    do_usb_passthrough

    if systemctl is-active --quiet display-manager.service; then
        systemctl stop display-manager.service
        while systemctl is-active --quiet display-manager.service; do
            sleep 1
        done
        defer "systemctl start display-manager.service"
    fi

    systemd-inhibit --what=sleep --mode=block sleep infinity &
    defer "kill $!"

    qemu-system-x86_64 "${opts_qemu[@]}" "$@"
}

main "$@"

