#!/bin/bash
set -e

__func_defered=()
defer() {
    __func_defered+=("$*")
}
do_defer() {
    for ((i=${#__func_defered[@]}-1;i>=0;i--)); do
        if ! eval "${__func_defered[i]}"; then
            echo "eval cmd failed, cmd: \"${__func_defered[i]}\"" >&2
        fi
    done
}
trap do_defer EXIT

main() {
    if [ $UID != 0 ]; then
        exec sudo "$0" "$@"
    fi
    if [ $PPID != 1 ]; then
        # install: yay -S --noconfirm daemonize
        mkdir -p log
        exec daemonize -c "$PWD" -v -o log/out.log -e log/err.log "$(realpath $0)" "$@"
    fi

    if systemctl is-active --quiet display-manager.service; then
        systemctl stop display-manager.service
        while systemctl is-active --quiet display-manager.service; do
            sleep 1
        done
        defer "systemctl start display-manager.service"
    fi

    local qemu_options=()
    qemu_options+=("-nodefaults" "-nographic" "-vga" "none")

    qemu_options+=("-enable-kvm")
    qemu_options+=("-cpu" "host,kvm=off")
    qemu_options+=("-smp" "cores=32")
    qemu_options+=("-m" "32G")
    qemu_options+=("-drive" "if=pflash,format=raw,readonly=on,file=/usr/share/edk2-ovmf/x64/OVMF_CODE.fd")

    # gpu passthrough
    virsh nodedev-detach pci_0000_01_00_0
    defer "virsh nodedev-reattach pci_0000_01_00_0"
    virsh nodedev-detach pci_0000_01_00_1
    defer "virsh nodedev-reattach pci_0000_01_00_1"
    qemu_options+=(
        "-device" "vfio-pci,host=01:00.0,x-vga=on,multifunction=on,romfile=${PWD}/assets/Gigabyte.RTX3090.24576.210315_3.rom"
        "-device" "vfio-pci,host=01:00.1"
    )

    # usb controller passthrough
    virsh nodedev-detach pci_0000_69_00_0
    defer "virsh nodedev-reattach pci_0000_69_00_0"
    qemu_options+=("-device" "vfio-pci,host=69:00.0")

    # nic
    qemu_options+=("-nic" "user")

    systemd-inhibit --what=sleep --mode=block sleep infinity &
    defer "kill $!"

    # anti detection
    qemu_options+=(
        "-machine" "pc-q35-7.1,accel=kvm,usb=off,vmport=off,kernel_irqchip=on,dump-guest-core=off,hpet=off,acpi=on"
        "-cpu" "host,migratable=on,topoext=on,hypervisor=off,hv-time=on,hv-relaxed=on,hv-vapic=on,hv-spinlocks=0x1fff,hv-vendor-id=123456789ab,kvm=off,kvm-hint-dedicated=on"

        "-smbios" 'type=0,vendor=American Megatrends Inc.,version=0309,date=08/16/2021,release=5.17'
        "-smbios" 'type=1,manufacturer=System manufacturer,product=System Product Name,version=System Version,serial=System Serial Number,sku=SKU,family=To be filled by O.E.M.'
        "-smbios" 'type=2,manufacturer=ASUSTeK COMPUTER INC.,product=ROG STRIX X570-E GAMING WIFI II,version=Rev X.0x,serial=210890780700315,asset=Default string,location=Default string'
        "-smbios" 'type=3,manufacturer=Default string,version=Default string,serial=Default string,asset=Default string,sku=Default string'
        "-smbios" 'type=11,value=Default string,value=Default string,value=Default string,value=Default string,value=Default string,value=Default string,value=Default string,value=Default string'

        "-global" "kvm-pit.lost_tick_policy=delay"
        "-global" "ICH9-LPC.disable_s3=1"
        "-global" "ICH9-LPC.disable_s4=1"
        "-global" "ICH9-LPC.noreboot=off"

        "-sandbox" "on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny"
    )

    qemu-system-x86_64 "${qemu_options[@]}" "$@"
}

main "$@"

# # disk
# qemu_args+=(
#     "-drive" "file=/dev/nvme1n1p1,if=virtio,media=disk,cache=unsafe,format=raw"
# )
