#!/bin/bash
set -x

object_name="$1"
operation="$2"
sub_operation="$3"
extra_arg="$4"

if systemctl is-active --quiet display-manager.service ; then
    systemctl stop display-manager.service
    while systemctl is-active --quiet display-manager.service ; do
        sleep 1
    done
fi
    
for vtc in /sys/class/vtconsole/vtcon*; do
    echo 0 > $vtc/bind
done

echo efi-framebuffer.0 > /sys/bus/platform/drivers/efi-framebuffer/unbind

sleep 2

for dev in pci_0000_0a_00_0 pci_0000_0a_00_1; do
    virsh nodedev-detach $dev
done

systemctl start libvirt-nosleep@$object_name
